services:

  postgres:
    image: postgres:17
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"

  order-service:
    build: ./order-service
    ports:
      - "3004:3004"

  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth-service
      - product-service
      - order-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway