services:

  postgres:
    image: postgres:17
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    ports:
      - "AUTH_PORT:AUTH_PORT"
    environment:
      AUTH_PORT: ${AUTH_PORT}
      AUTH_DATABASE_URL: ${AUTH_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - postgres

  product-service:
    build: ./product-service
    ports:
      - "PRO_PORT:PRO_PORT"
    environment:
      PRO_PORT: ${PRO_PORT}
      PRODUCT_DATABASE_URL: ${PRODUCT_DATABASE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}

  order-service:
    build: ./order-service
    ports:
      - "ORDER_PORT:ORDER_PORT"
    environment:
      ORDER_PORT: ${ORDER_PORT}
      ORDER_DATABASE_URL: ${ORDER_DATABASE_URL}

  api-gateway:
    build: ./api-gateway
    ports:
      - "API_PORT:API_PORT"
    environment:
      API_PORT: ${API_PORT}
      AUTH_API_URL: ${AUTH_API_URL}
      PRO_API_URL: ${ PRO_API_URL}
      ORDER_API_URL: ${ORDER_API_URL}
      FRO_API_URL: ${FRO_API_URL}
    depends_on:
      - auth-service
      - product-service
      - order-service

  frontend:
    build: ./frontend
    ports:
      - "FRO_PORT:FRO_PORT"
    environment:
      FRO_PORT: ${FRO_PORT}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - api-gateway